const id = "02-astro-sphere-getting-started/index.md";
						const collection = "blog";
						const slug = "02-astro-sphere-getting-started";
						const body = "\r\nAstro Sphere is designed to be configurable. This article will cover the basics on\r\nconfiguring the site and make it personal.\r\n\r\n### First let's change the url\r\n\r\n```js\r\n//astro.config.mjs\r\n\r\nexport default defineConfig({\r\n  site: \"https://astro-sphere.vercel.app\", // your domain here\r\n  integrations: [mdx(), sitemap(), solidJs(), tailwind({ applyBaseStyles: false })],\r\n})\r\n```\r\n\r\n### Next, Let's configure the Site\r\n\r\n```js\r\n// src/consts.ts\r\n\r\nexport const SITE: Site = {\r\n  TITLE: \"Astro Sphere\",\r\n  DESCRIPTION: \"Welcome to Astro Sphere, a portfolio and blog for designers and developers.\",\r\n  AUTHOR: \"Mark Horn\",\r\n}\r\n```\r\n\r\n| Field       | Type   | Description                                                            |\r\n| :---------- | :----- | :--------------------------------------------------------------------- |\r\n| TITLE       | String | The title of the website. Displayed in header and footer. Used in SEO. |\r\n| DESCRIPTION | String | The description of the index page of the website. Used in SEO.         |\r\n| AUTHOR      | String | Your name.                                                             |\r\n\r\n### Change the branding\r\n\r\nThe browser icon is located in `/public/favicon.svg`\r\n\r\nThe header and footer branding icon is located in `/public/brand.svg` as a sprite with id=\"brand\"\r\n\r\n### The rest of the consts file\r\n\r\nEach page has a metadata entry that is useful for SEO.\r\n\r\n```js\r\nexport const WORK: Page = {\r\n  TITLE: \"Work\",\r\n  DESCRIPTION: \"Places I have worked.\",\r\n}\r\n```\r\n\r\nThe links that are displayed in the header and drawer\r\n\r\n```js\r\nexport const LINKS: Links = [\r\n  { HREF: \"/\", TEXT: \"Home\" },\r\n  { HREF: \"/work\", TEXT: \"Work\" },\r\n  { HREF: \"/blog\", TEXT: \"Blog\" },\r\n  { HREF: \"/projects\", TEXT: \"Projects\" },\r\n]\r\n```\r\n\r\nThe social media links\r\n\r\n```js\r\nexport const SOCIALS: Socials = [\r\n  { \r\n    NAME: \"Github\",\r\n    ICON: \"github\",\r\n    TEXT: \"markhorn-dev\",\r\n    HREF: \"https://github.com/markhorn-dev/astro-sphere\"\r\n  },\r\n]\r\n```\r\n\r\n| Field | Type | Required | Description |\r\n| :---- | :--- | :------- | :---------- |\r\n| NAME  | string | yes | Accessible name |\r\n| ICON  | string | yes | Refers to the symbol id in `public/social.svg` |\r\n| TEXT  | string | yes | Shorthand profile name |\r\n| HREF  | string | yes | The link to the social media profile |";
						const data = {title:"Astro Sphere: Getting Started",summary:"You've downloaded and installed the project. Let's hit the ground running.",date:new Date(1710514800000),tags:["Tutorial","Astro","Astro Sphere"],draft:false};
						const _internal = {
							type: 'content',
							filePath: "/mnt/c/Users/souic/Documents/DSFA/DSFA/src/content/blog/02-astro-sphere-getting-started/index.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
