const id = "01-astro-sphere-file-structure/index.md";
						const collection = "blog";
						const slug = "01-astro-sphere-file-structure";
						const body = "\r\nA one line summary of what each file and directory is for:\r\n```js\r\n/\r\n├── public/ // Files publicly available to the browser\r\n│   ├── fonts/ // The default fonts for Astro Sphere\r\n│   │   └── atkinson-bold.woff  // default font weight 700\r\n│   │   └── atkinson-regular.woff // default font weight 400\r\n│   ├── js/ // Javascript that will be imported into <head>\r\n│   │   └── animate.js // function for animating page elements\r\n│   │   └── bg.js // function for generating the background\r\n│   │   └── scroll.js // scroll handler for the header styles\r\n│   │   └── theme.js // controls the light and dark theme\r\n│   └── brand.svg //the icon that displays in header and footer\r\n│   └── favicon.svg //the icon that displays in the browser\r\n│   └── ui.svg // an svg sprite for all ui icons on the website\r\n│   └── social.svg // an svg sprite for all social media icons\r\n│   └── open-graph.jpg // the default image for open-graph\r\n│   └── robots.txt // for web crawlers and bots to index the website\r\n├── src/ // Everything that will be built for the website\r\n│   ├── components/ // All astro and SolidJs components\r\n│   ├── content/ // Contains all static markdown to be compiled\r\n│   │   |  blog/ // Contains all blog post markdown\r\n│   │   |  projects/ // Contains all projects markdown\r\n│   │   |  work/ // Contains all work page markdown\r\n│   │   |  legal/ // Contains all legal docs markdown\r\n│   │   └── config.ts // Contains the collection config for Astro\r\n│   ├── layouts/ // Reused layouts across the website\r\n│   └── pages/ // All of the pages on the website\r\n│   └── styles/ // CSS and global tailwind styles\r\n│   └── lib/ // Global helper functions\r\n│   └── consts.ts // Page metadata, general configuration\r\n│   └── types.ts // Types for consts.ts\r\n└── .gitignore // Files and directories to be ignored by Git\r\n└── .eslintignore // Files and directories to be ignored by ESLint\r\n└── eslintrc.cjs // ESLint configuration\r\n└── astro.config.mjs // Astro configuration\r\n└── tailwind.config.mjs // Tailwind configuration\r\n└── tsconfig.json // Typescript configuration\r\n└── package.json // All the installed packages\r\n```";
						const data = {title:"Astro Sphere: File Structure",summary:"You'll find these directories and files in the project. What do they do?",date:new Date(1710601200000),tags:["Tutorial","Astro","Astro Sphere"],draft:false};
						const _internal = {
							type: 'content',
							filePath: "/mnt/c/Users/souic/Documents/DSFA/DSFA/src/content/blog/01-astro-sphere-file-structure/index.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
