const id = "project-4/index.md";
						const collection = "projects";
						const slug = "project-4";
						const body = "\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra. Adipiscing enim eu turpis egestas pretium. \r\n\r\nEuismod elementum nisi quis eleifend quam adipiscing. In hac habitasse platea dictumst vestibulum. Sagittis purus sit amet volutpat. Netus et malesuada fames ac turpis egestas. \r\n\r\nEget magna fermentum iaculis eu non diam phasellus vestibulum lorem. \r\nVarius sit amet mattis vulputate enim. Habitasse platea dictumst quisque sagittis. Integer quis auctor elit sed vulputate mi. Dictumst quisque sagittis purus sit amet.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra. Adipiscing enim eu turpis egestas pretium. \r\n\r\nEuismod elementum nisi quis eleifend quam adipiscing. In hac habitasse platea dictumst vestibulum. Sagittis purus sit amet volutpat. Netus et malesuada fames ac turpis egestas. \r\n\r\nEget magna fermentum iaculis eu non diam phasellus vestibulum lorem. \r\nVarius sit amet mattis vulputate enim. Habitasse platea dictumst quisque sagittis. Integer quis auctor elit sed vulputate mi. Dictumst quisque sagittis purus sit amet.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra. Adipiscing enim eu turpis egestas pretium. \r\n\r\nEuismod elementum nisi quis eleifend quam adipiscing. In hac habitasse platea dictumst vestibulum. Sagittis purus sit amet volutpat. Netus et malesuada fames ac turpis egestas. \r\n\r\nEget magna fermentum iaculis eu non diam phasellus vestibulum lorem. \r\nVarius sit amet mattis vulputate enim. Habitasse platea dictumst quisque sagittis. Integer quis auctor elit sed vulputate mi. Dictumst quisque sagittis purus sit amet.";
						const data = {title:"Project Four",summary:"Lorem ipsum dolor sit amet",date:new Date(1647270000000),tags:["React","Javascript","StyleX"],draft:false};
						const _internal = {
							type: 'content',
							filePath: "/mnt/c/Users/souic/Documents/DSFA/DSFA/src/content/projects/project-4/index.md",
							rawData: undefined,
						};

export { _internal, body, collection, data, id, slug };
